export const APP_NAME = "Glipz";
export const APP_VERSION = "0.0.2";

export const FEDERATION_PROTOCOL_NAME = "glipz-federation";
export const FEDERATION_PROTOCOL_VERSION = `${FEDERATION_PROTOCOL_NAME}/3`;
export const FEDERATION_SUPPORTED_PROTOCOL_VERSIONS = [`${FEDERATION_PROTOCOL_NAME}/2`, FEDERATION_PROTOCOL_VERSION] as const;
export const FEDERATION_EVENT_SCHEMA_VERSION = 3;
